[OneBot] Refactoring RecordSegment
LagrangeDev/Lagrange.Core pull request #441
Opened 2024-07-11 20:44 UTC by DarkCWK

2024-07-12 09:06 UTC, Executor-Cheng requested changes
以上
由于你在更改 public 方法签名, 也应当要求你先不更改原签名, 转为标注 `[Obsolete]` 特性告知用户, 将新的方法以另外的名称添加进去

2024-07-12 09:06 UTC, Executor-Cheng commented on Lagrange.OneBot/Utility/AudioHelper.cs
> +        if (value == 0x52494646 && BinaryPrimitives.ReadUInt32BigEndian(data.AsSpan(8, sizeof(uint))) == 0x57415645)
不准偷懒, 15个字节全都要比较

2024-07-16 18:07 UTC, Linwenxuan04 approved these changes

2024-07-17 17:52 UTC, Executor-Cheng approved these changes
先这样吧

2024-07-17 18:10 UTC, merged