[All] new firend group
LagrangeDev/Lagrange.Core pull request #477
Opened 2024-07-31 06:06 UTC by DarkCWK

2024-08-04 12:16 UTC, Linwenxuan04 requested changes

2024-08-04 12:16 UTC, Linwenxuan04 commented on Lagrange.Core/Common/Entity/BotFriend.cs
把GroupName和GroupId封装一个struct
并且让他们可以是default

2024-08-04 12:16 UTC, Linwenxuan04 commented on Lagrange.Core/Common/Entity/BotFriend.cs
这样就不会在下面污染constrctor
毕竟下面有些实现怪怪的

2024-08-04 12:16 UTC, Linwenxuan04 commented on Lagrange.Core/Internal/Packets/Service/Oidb/Generics/OidbGroup.cs
有一个OidbProperty 用那个 而并非新建一个类型

2024-08-05 13:09 UTC, Executor-Cheng commented
由于 Author 注销账号, 暂时关闭此 PR

2024-08-12 17:45 UTC, CwkDark commented
我接手了

2024-08-13 15:43 UTC, closed without merging