[OneBot] fix Sending message failed but still returns success
LagrangeDev/Lagrange.Core pull request #479
Opened 2024-08-04 13:39 UTC by DarkCWK

2024-08-04 13:59 UTC, ishkong commented
retcode改成-1000吧，纪念一下死去的酷Q（x
-1000表示发生未知错误（你应该看日志了

2024-08-04 14:03 UTC, ishkong requested changes

2024-08-04 14:03 UTC, ishkong commented on Lagrange.OneBot/Core/Operation/Message/SendGroupForwardOperation.cs
> +            return new OneBotResult(new OneBotForwardResponse(hash, multi.ResId ?? ""), (int)result.Result, "ok");
这里retcode是不是该为0

https://github.com/botuniverse/onebot-11/blob/d4456ee706f9ada9c2dfde56a2bcfc69752600e4/communication/http.md?plain=1#L61

2024-08-05 13:09 UTC, Executor-Cheng commented
由于 Author 注销账号, 暂时关闭此 PR

2024-08-18 16:50 UTC, CwkDark approved these changes

2024-08-19 11:15 UTC, ishkong approved these changes

2024-08-19 16:06 UTC, KusaGumina commented
Unsigned,Close

2024-08-19 16:06 UTC, closed without merging