[Core] Fix GroupGreyTipNotice may not have `action_str`
LagrangeDev/Lagrange.Core pull request #523
Opened 2024-08-19 14:50 UTC by ishkong

2024-08-19 15:49 UTC, KusaGumina approved these changes

2024-08-20 05:12 UTC, CwkDark approved these changes

2024-08-20 08:31 UTC, Executor-Cheng requested changes

2024-08-20 08:31 UTC, Executor-Cheng commented on Lagrange.Core/Internal/Service/Message/PushMessageService.cs
> +                    var groupPokeEvent = GroupSysPokeEvent.Result(groupUin, uint.Parse(templates["uin_str1"]), uint.Parse(templates["uin_str2"]), actionStr ?? string.Empty, templates["suffix_str"]);
上边的 `if` 块已经保证了 `actionStr` 不为 `null`, 因此 `actionStr ?? string.Empty` 是多余操作

2024-08-20 09:04 UTC, closed without merging