[Core] Group clock in 群打卡
LagrangeDev/Lagrange.Core pull request #528
Opened 2024-08-19 21:11 UTC by dogdie233

有几个问题

1. 这个包似乎不需要sign都能用，就没加`SignProvider`的`WhiteListCommand`，要加吗
2. `OidbSvcTrpcTcp0xEB7_1` 这个包的第三个字段(AppVersion)，实测不加也不会影响结果，要删吗

2024-08-21 23:30 UTC, pk5ls20 commented
> 有几个问题
> 
> 1. 这个包似乎不需要sign都能用，就没加`SignProvider`的`WhiteListCommand`，要加吗
> 2. `OidbSvcTrpcTcp0xEB7_1` 这个包的第三个字段(AppVersion)，实测不加也不会影响结果，要删吗

不需要sign就不用加到`WhiteListCommand`啊

2024-08-22 05:07 UTC, Linwenxuan04 requested changes

2024-08-22 05:07 UTC, Linwenxuan04 commented on Lagrange.Core/Internal/Service/Action/GroupClockInService.cs
> +[Service("OidbSvcTrpcTcp.0xeb7")]
为什么这个包的Command没有OIdb subCmd，是没有还是没写上（

2024-08-22 05:42 UTC, dogdie233 commented on Lagrange.Core/Internal/Service/Action/GroupClockInService.cs
> +[Service("OidbSvcTrpcTcp.0xeb7")]
漏了（）

2024-08-23 12:06 UTC, Linwenxuan04 approved these changes

2024-08-23 12:06 UTC, merged