[All] Add CreateGroupFolderOp & adjust DeleteGroupFolderOp
LagrangeDev/Lagrange.Core pull request #540
Opened 2024-08-22 06:30 UTC by pk5ls20

2024-08-22 06:40 UTC, pk5ls20 commented
may resolve #396

2024-08-23 12:05 UTC, Linwenxuan04 requested changes

2024-08-23 12:05 UTC, Linwenxuan04 commented on Lagrange.Core/Common/Interface/Api/GroupExt.cs
> +    public static Task<KeyValuePair<int, string>> GroupFSCreateFolder(this BotContext bot, uint groupUin, string name)
Use () instead of KeyValuePair

2024-08-23 12:05 UTC, Linwenxuan04 commented on Lagrange.Core/Common/Interface/Api/GroupExt.cs
> +    public static Task<KeyValuePair<int, string>> GroupFSDeleteFolder(this BotContext bot, uint groupUin, string folderId)
Use () instead of KeyValuePair

2024-08-23 12:14 UTC, Linwenxuan04 approved these changes

2024-08-23 12:14 UTC, merged