[Core] Add friend shake in private chat
LagrangeDev/Lagrange.Core pull request #547
Opened 2024-08-23 22:21 UTC by dogdie233

2024-08-23 22:31 UTC, dogdie233 commented
- `FriendShakeEntity` 修改Extra的`FaceId`没用，但他们好像会一起变，就一起写了，要修改`BusinessType`的值
 - `FriendSpecialShakeEntity` 只修改Extra的`FaceId`好像就可以了，但他们好像会一起变，就一起写了

测试当前Linux协议如下
|  | 窗口抖动的`戳一戳` | 除`戳一戳`外的窗口抖动 | 特殊窗口抖动 |
| --- |  --- | --- | --- |
| 发送 | √ | √ | √ | 
| 接收 | √ | × | √ |

接收 __除`戳一戳`外的窗口抖动__ 时只存在`TextEntity`

2024-08-30 08:45 UTC, CwkDark commented
![image](https://github.com/user-attachments/assets/11126b69-c903-4516-b5f0-61d51ffaecb7)

这里是不是重复了？

2024-08-30 15:36 UTC, dogdie233 commented
> ![image](https://private-user-images.githubusercontent.com/177549718/363105423-0a4cd390-3f46-4ecf-a14c-2f87baa4c57b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMzI0MzEsIm5iZiI6MTcyNTAzMjEzMSwicGF0aCI6Ii8xNzc1NDk3MTgvMzYzMTA1NDIzLTBhNGNkMzkwLTNmNDYtNGVjZi1hMTRjLTJmODdiYWE0YzU3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQxNTM1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWRmMDdmNTRkYTJlZGJhNGZjMThmMDFkOTNiNTRjYzI2M2NmZWQ1Yzg5Y2VlZWIxYWViOWQ4NGFiOWQxNDA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MiXSBpUpPC_9DtRQWIyTSwzLmMSVIbRY5Tsx_vCYriI)
> 
> 这里是不是重复了？

确实，这条信息也被解析成poke了，不确定要不要改，

2024-08-30 17:24 UTC, dogdie233 commented
`Lagrange.Core.Message.Entity.PokeEntity`的`IMessageEntity.UnpackElement`解析了ServiceType: 2, BusinessType: 1的情况，但是自己测了一下发现，接收拍一拍似乎不是通过这个地方解析的？不懂这个是什么情况

2024-08-31 05:00 UTC, CwkDark commented
> 但是自己测了一下发现，接收拍一拍似乎不是通过这个地方解析的？

测试了可以断在这个位置

2024-08-31 17:02 UTC, dogdie233 commented
老public api不好改，我先标记obsolete，康康lwx怎么说

2024-08-31 17:30 UTC, dogdie233 commented
干脆还是改回Poke好了）
反正一直都是这么用的

2024-09-05 03:06 UTC, Executor-Cheng requested changes
以上

2024-09-05 03:06 UTC, Executor-Cheng commented on Lagrange.Core/Message/Entity/PokeEntity.cs
>      IEnumerable<Elem> IMessageEntity.PackElement()
使用 `yield` 会为此方法创建状态机
在返回少数且固定数量的情况下, 原先的方法更优

2024-09-05 03:06 UTC, Executor-Cheng commented on Lagrange.Core/Message/Entity/SpecialPokeEntity.cs
> +    IEnumerable<Elem> IMessageEntity.PackElement()
同上

2024-09-06 03:16 UTC, Executor-Cheng approved these changes

2024-09-06 03:16 UTC, merged