[Core] Fix the issue of sending super emoticons and some other normal emoticons
LagrangeDev/Lagrange.Core pull request #618
Opened 2024-09-30 21:06 UTC by pk5ls20

resolve #367

2024-10-09 03:45 UTC, dogdie233 commented
@Linwenxuan04

2024-10-09 03:45 UTC, dogdie233 approved these changes

2024-10-09 03:53 UTC, pk5ls20 commented
还没写完，先别合（

> @Linwenxuan04

2024-10-22 07:23 UTC, Linwenxuan04 requested changes

2024-10-22 07:23 UTC, Linwenxuan04 commented on Lagrange.Core/Internal/Service/Action/JoinEmojiChainService.cs
> +internal class FetchClientKeyService : BaseService<JoinEmojiChainEvent>
Rename Service

2024-10-22 07:23 UTC, Linwenxuan04 commented on Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
> +        string targetDirectory)
Remove useless changes

2024-10-22 07:31 UTC, Linwenxuan04 approved these changes

2024-10-22 07:31 UTC, merged