feat: Create all API cancellable (Login not completed)
LagrangeDev/Lagrange.Core pull request #630
Opened 2024-10-07 03:38 UTC by dogdie233

2024-10-07 07:31 UTC, dogdie233 commented
lwx说WtLogin的那块他来改喵

2024-10-08 10:00 UTC, dogdie233 commented
把lwx的修改抄过来了

2024-10-08 11:45 UTC, Executor-Cheng requested changes
总结:
1. 请将 `CancellationToken` 参数放到最后一个
2. 请统一 `CancellationToken` 参数名
3. 需要为 SocketContext 和 ClientListener 的 Send 方法增加 CancellationToken 支持
4. 尽量使用到方法传入的 `CancellationToken`, 如果上下文本身有一个 `CancellationToken`, 可以使用 `CancellationTokenSource.CreateLinkedTokenSource` 创建联合的取消源
5. 有些文件没有标注上述需要更改的点, 麻烦自己查一下

2024-10-08 11:45 UTC, Executor-Cheng commented on Lagrange.Core/Common/Interface/Api/OperationExt.cs
请将 `CancellationToken` 参数放到最后一个
`Task<List<BotFriend>> FetchFriends(this BotContext bot, bool refreshCache = false)`
`Task<List<BotFriend>> FetchFriends(this BotContext bot, bool refreshCache, CancellationToken ct)`

这样当用户调用 `bot.FetchFriends()` 时仍会调用第一个重载, 然后第一个重载调用第二个重载的时候会给定正确的参数

2024-10-08 11:45 UTC, Executor-Cheng commented on Lagrange.Core/Internal/Context/HighwayContext.cs
同上, 另外请统一 `CancellationToken` 参数名

2024-10-08 11:45 UTC, Executor-Cheng commented on Lagrange.Core/Internal/Context/Logic/Implementation/CachingLogic.cs
同上

2024-10-08 11:45 UTC, Executor-Cheng commented on Lagrange.Core/Internal/Context/Logic/Implementation/WtExchangeLogic.cs
> +    public override async Task Incoming(ProtocolEvent e, CancellationToken _)
既然在这里加了 `CancellationToken` 参数, 为什么不使用呢?

2024-10-08 11:45 UTC, Executor-Cheng commented on Lagrange.Core/Internal/Context/Logic/Implementation/WtExchangeLogic.cs
> +            await Collection.Business.PushEvent(AliveEvent.Create(), CancellationToken.None);
这里也没有使用捕获的 `ct`

2024-10-08 11:45 UTC, Executor-Cheng commented on Lagrange.Core/Internal/Context/Logic/Implementation/WtExchangeLogic.cs
整一个文件都没有使用方法传入的 `CancellationToken`, 逻辑上不太对

2024-10-08 11:45 UTC, Executor-Cheng commented on Lagrange.Core/Internal/Context/PacketContext.cs
适应本 PR 更改时, 需要为 `SocketContext` 和 `ClientListener` 的 `Send` 方法增加 `CancellationToken` 支持, 现在这样改太别扭了

2024-10-08 11:45 UTC, Executor-Cheng commented on Lagrange.Core/Utility/Network/Http.cs
> +        var response = await Client.PostAsync(url, contentData, ct);
这个 `response` 需要 Dispose

2024-10-08 14:21 UTC, dogdie233 commented on Lagrange.Core/Internal/Context/PacketContext.cs
tcpClient没有cancellationToken欸，而且逻辑上如果数据包发送到一半直接cancel掉的话，那上下文应该就不对了（比如长度包头114514，只发了114个字节就取消了）
所以就没有给SocketContext加cancellationToken

2024-10-08 14:22 UTC, dogdie233 commented on Lagrange.Core/Internal/Context/PacketContext.cs
或者cancel掉就关闭tcp连接走重连
但是感觉这样也有点怪

2024-10-08 16:21 UTC, dogdie233 commented on Lagrange.Core/Internal/Context/Logic/Implementation/WtExchangeLogic.cs
> +    public override async Task Incoming(ProtocolEvent e, CancellationToken _)
因为没有要用到的喵，这里是因为继承需要

2024-10-21 14:05 UTC, Executor-Cheng approved these changes
LGTM

2024-10-21 14:15 UTC, merged