完善 get_stranger_info
LagrangeDev/Lagrange.Core pull request #631
Opened 2024-10-11 15:18 UTC by sisi0318

![download](https://github.com/user-attachments/assets/e169b189-e184-4de1-a0bf-00efe6d2110d)

2024-10-11 15:21 UTC, Redmomn approved these changes

2024-10-11 17:09 UTC, DarkRRb requested changes
希望可以格式化

2024-10-11 17:09 UTC, DarkRRb commented on Lagrange.OneBot/Core/Operation/Info/GetStrangerInfoOperation.cs
> +            };
应设置为静态变量

2024-10-11 17:09 UTC, DarkRRb commented on Lagrange.OneBot/Core/Operation/Info/GetStrangerInfoOperation.cs
> +                string? Statusmsg = StatusArray.TryGetValue(status, out string? value) ? value : "未知状态";
是否无需 "?" ?

2024-10-12 01:25 UTC, sisi0318 commented
> 希望可以格式化

我不会 理直气壮.jpg

2024-10-12 05:32 UTC, DarkRRb approved these changes

2024-10-12 05:32 UTC, merged