[All] AiRecord
LagrangeDev/Lagrange.Core pull request #670
Opened 2024-11-01 14:48 UTC by Decrabbityyy

2024-11-01 15:32 UTC, DarkRRb requested changes

2024-11-01 15:32 UTC, DarkRRb commented on Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
> +    public async Task<(List<AiCharacterList>? Result,string ErrMsg)> GetAiCharacters(uint chatType,uint groupUin)
Unify the return value style

2024-11-02 12:17 UTC, Executor-Cheng requested changes

2024-11-02 12:17 UTC, Executor-Cheng commented on Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
> +            (uint)(result.MessageId & uint.MaxValue), result.Timestamp);
多余的与操作

2024-11-02 12:17 UTC, Executor-Cheng commented on Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
> +            (uint)(chain.MessageId & uint.MaxValue), timestamp);
多余的与操作

2024-11-02 12:17 UTC, Executor-Cheng commented on Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
> +        }
对于多次访问同一偏移实例的, 请定义局部变量

2024-11-02 12:17 UTC, Executor-Cheng commented on Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
> +        return (result.ResultCode, result.ErrorMessage, result.AiCharacters);
return (result.ResultCode, result.ErrorMessage, result.ResultCode != 0 ? null : result.AiCharacters);

2024-11-02 12:17 UTC, Executor-Cheng commented on Lagrange.Core/Internal/Event/Action/FetchAiCharacterListEvent.cs
> +    private FetchAiCharacterListEvent(uint chatType, uint groupUin = 42) : base(true)
这个 42 的默认值是正确的不

2024-11-02 12:17 UTC, Executor-Cheng commented on Lagrange.Core/Internal/Service/Action/GroupAiRecordService.cs
> +        }
output = GroupAiRecordEvent.Result(0, payload.Body.MsgInfo);

2024-11-02 12:17 UTC, Executor-Cheng commented on Lagrange.OneBot/Core/Entity/Action/OneBotGetAiCharacters.cs
> +    [JsonPropertyName("group_id")] public uint GroupId { get; set; } = 42;
这里的 42 也是正确的不

2024-11-02 12:25 UTC, sisi0318 commented on Lagrange.Core/Internal/Event/Action/FetchAiCharacterListEvent.cs
> +    private FetchAiCharacterListEvent(uint chatType, uint groupUin = 42) : base(true)
原本在手机协议上 群号指定是有意义的 因为手机上是直接发出去 但是到ntqq 直接发出去报废了 所以 默认指定一个理论没问题

2024-11-02 12:29 UTC, Decrabbityyy commented on Lagrange.OneBot/Core/Entity/Action/OneBotGetAiCharacters.cs
> +    [JsonPropertyName("group_id")] public uint GroupId { get; set; } = 42;
缺省个默认值方便调用

2024-11-02 13:10 UTC, DarkRRb commented on Lagrange.Core/Internal/Event/Action/FetchAiCharacterListEvent.cs
> +    private FetchAiCharacterListEvent(uint chatType, uint groupUin = 42) : base(true)
经过测试, 此字段不写都行

2024-11-03 02:38 UTC, sisi0318 commented
怎么还不合 急急急

2024-11-03 03:39 UTC, Executor-Cheng approved these changes

2024-11-03 03:44 UTC, DarkRRb approved these changes

2024-11-03 03:45 UTC, merged