[OneBot] Making API `get_group_honor_info` returns Onebot11 compliant
LagrangeDev/Lagrange.Core pull request #679
Opened 2024-11-05 07:07 UTC by ishkong

fix #675

2024-11-08 06:41 UTC, DarkRRb approved these changes

2024-11-08 06:41 UTC, DarkRRb commented on Lagrange.OneBot/Core/Operation/Group/GetGroupHonorInfoOperation.cs
> +                            if (honor.Type == "all" || key.Contains(honor.Type)) result.TryAdd(key, jsonArray.Deserialize<JsonNode>());
使用 all 的时候由于每次请求都有全部列表的 key, 对应 value 的是空列表

因此这里使用 TryAdd 的话, 会导致后面的列表都无法插入进去, 因为 key 已经存在了

建议判断 key 只添加对应的列表

2024-11-08 06:41 UTC, DarkRRb commented on Lagrange.OneBot/Core/Operation/Group/GetGroupHonorInfoOperation.cs
> +                        if (json[value] is JsonObject jsonObject)                                                                            // 神经病 (我也觉得)
为什么好长好长好长的空格

2024-11-08 06:43 UTC, DarkRRb requested changes
刚刚点错了（（（

2024-11-08 09:11 UTC, Executor-Cheng requested changes

2024-11-08 09:11 UTC, Executor-Cheng commented on Lagrange.OneBot/Core/Operation/Group/GetGroupHonorInfoOperation.cs
试试 jsonObject.Remove(oldKey, out var nodeValue)
一个 `JsonNode` 必须先从父 Node 中移除后才能添加到另一个 `JsonObject` / `JsonArray`
你在 `ProcessJsonObject` 里已经尝试过以上了, 同样地应用进 `HandleOperation` 方法即可

2024-11-10 07:48 UTC, Executor-Cheng requested changes

2024-11-10 07:48 UTC, Executor-Cheng commented on Lagrange.OneBot/Core/Operation/Group/GetGroupHonorInfoOperation.cs
> +                        }
这一部分也可以用 `Remove` 移花接木的

2024-11-12 14:12 UTC, Executor-Cheng commented on Lagrange.OneBot/Core/Operation/Group/GetGroupHonorInfoOperation.cs
> +                        }
```csharp
if (json.Remove(value, out var node))
{
	result.TryAdd(key, node);
}
```
不知道你判断 `honor.Type` 是有什么用意

2024-11-12 14:55 UTC, Executor-Cheng approved these changes

2024-11-12 14:56 UTC, DarkRRb approved these changes

2024-11-12 14:58 UTC, merged